# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoProject
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'FLEX', :configurations => ['Debug']
end
